config/routes.rb
Rails.application.routes.draw do

  devise_for :farms, controllers: { omniauth_callbacks: "farm_callbacks" }
  devise_for :restaurants

  authenticated :farm do
    root "farms#index", as: :farm_root
    get "/" => "farms#index"
  end

  authenticated :restaurant do
    root "restaurants#index", as: :restaurant_root
    get "/" => "restaurants#index"
  end

  root "application#index"

  resources :categories, only: [:index]
  resources :items, only: [:index, :create, :show, :update, :destroy, :new, :edit]
  resources :baskets, only: [:index, :create, :destroy, :update]
  resources :charges, only: [:new, :create]
  resources :orders, only: [:index, :create, :show]

  get "/baskets/count" => "baskets#count"
  get "/inventory" => "items#farm_index", as: :farm_items
  get "/product/:id" => "items#product", as: :product
  get "/map" => "maps#index", as: :map
  get "/farms/:id/items" => "farms#show", as: :farms_items

end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_filter :authenticate_restaurant!

  def index
    @basket_items = current_restaurant.basket_items.includes(:item)
    @amount = (current_restaurant.basket_total * 1.2 * 100).to_i
  end

  def create
    basket_item = current_restaurant.basket_items.create(basket_item_params)
    render json: basket_item
  end

  def destroy
    basket_item = current_restaurant.basket_items.find(params[:id])
    basket_item.destroy
    render json: basket_item
  end

  def count
    total_ex_vat = current_restaurant.basket_total
    vat = 1.2
    total_inc_vat = total_ex_vat * vat

    render json: {count:       current_restaurant.basket_items.count,
                  totalExVat:  total_ex_vat.round(2),
                  vat:         20,
                  totalIncVat: total_inc_vat.round(2)}
  end

  def basket_item_params
    params.require(:basket_item).permit(:item_id, :quantity)
  end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/views/baskets/index.html.haml
= render "page_title", title_text: "My Basket"

- if current_restaurant.basket_items.count > 0

  .basketItemsContainer{"ng-controller": "BasketsCtrl"}
    .basketTable
      %table{class: "striped responsive-table"}
        %thead
          %tr
            %th{class: "itemName"} Item
            %th{class: "itemQuantity"} Quantity
            %th{class: "itemPrice"} Price
            %th{class: "itemTotal"} Total
          %tbody
            %tr{"ng-repeat": "basket_item in basket_items"}
              %td{"ng-bind": "basket_item.item.name"}
              %td{"ng-bind": "basket_item.quantity"}
              %td{"ng-bind-template": "£ {{basket_item.item.price}}"}
              %td{"ng-bind": "basket_item.total"}
              %td
                %a{class: "removeLink waves-effect waves-light btn red", "ng-click": "removeFromBasket(basket_item.id)"} Remove

    .row
      .total{class: "subTotals col s4 offset-s8"}
        .labels
          .totalExLabel Total (ex Vat)
          .vatLabel VAT
          .totalIncLabel (inc Vat)
        .totals
          .totalExLabel
            %span{class: "totalVal", id: "totalExVat", "ng-bind-template": "£ {{totalExVat}}"}
          .vatLabel
            %span{class: "totalVal", id: "vat", "ng-bind-template": "{{vat}}%"}
          .totalIncLabel
            %span{class: "totalVal", id: "totalIncVat", "ng-bind-template": "£ {{totalIncVat}}"}

  .row
    .payButton{class: "col s3 push-s10"}
      = form_tag charges_path do
        %article
          - if flash[:error].present?
            #error_explanation
              %p= flash[:error]
        %script.stripe-button{"data-amount" => "#{@amount}", "data-description" => "Farm Fresh Order", "data-key" => Rails.configuration.stripe[:publishable_key], "data-locale" => "auto", :src => "https://checkout.stripe.com/checkout.js", "data-image" => "https://s3-eu-west-1.amazonaws.com/kpfarmfresh/logo.png", "data-currency" => "gbp", "data-email" => "#{current_restaurant.email}"}
-else
  .row
    .section
      %h4 Your basket is empty