config/routes.rb
Rails.application.routes.draw do

  devise_for :farms, controllers: { omniauth_callbacks: "farm_callbacks" }
  devise_for :restaurants

  authenticated :farm do
    root "farms#index", as: :farm_root
    get "/" => "farms#index"
  end

  authenticated :restaurant do
    root "restaurants#index", as: :restaurant_root
    get "/" => "restaurants#index"
  end

  root "application#index"

  resources :categories, only: [:index]
  resources :items, only: [:index, :create, :show, :update, :destroy, :new, :edit]
  resources :baskets, only: [:index, :create, :destroy, :update]
  resources :charges, only: [:new, :create]
  resources :orders, only: [:index, :create, :show]

  get "/baskets/count" => "baskets#count"
  get "/inventory" => "items#farm_index", as: :farm_items
  get "/product/:id" => "items#product", as: :product
  get "/map" => "maps#index", as: :map
  get "/farms/:id/items" => "farms#show", as: :farms_items

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :farm
  belongs_to :category
  has_many :images, class_name: 'ItemImage', foreign_key: :item_id
  has_many :line_items

  validates_presence_of :name, :category, :farm
  validates :price, numericality: { greater_than: 0}

  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true

  before_create :default_values
  before_destroy :archive_item

  scope :live,    -> { where archived: false }
  scope :archive, -> { where archived: true }

  private

  def default_values
    write_attribute(:archived, false)
    write_attribute(:created_at, DateTime.now)
  end

  def archive_item
    write_attribute(:archived, true)
    false
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_restaurant!, only: [:index, :product]
  before_filter :authenticate_farm!, only: [:farm_index, :create, :destroy, :new, :edit]

  def index
    sort_column =
      params[:sort_option].nil? ? :price : params[:sort_option].strip.downcase

    if params[:category_id].nil?
      @items = Item.order({ sort_column.to_sym => "DESC" }).
        paginate(page: params[:page], per_page: 9).
        includes(:images)
    else
      @items = Category.find(params[:category_id]).
        items.order({ sort_column.to_sym => "DESC" }).
        paginate(page: params[:page], per_page: 9).
        includes(:images)
    end

  end

  def show
    @item = Item.find(params[:id])
  end


  def create
    @item = Item.create(item_params)

    if @item.valid?
      current_farm.tweet("#{@item.quantity} #{@item.name} at £#{@item.price} each, http://bit.ly/1UZlvPK")
      redirect_to farm_items_path, notice: "Item created"
    else
      redirect_to farm_items_path, notice: "Could not create item"
    end

  end

  def destroy
    @item = Item.find(params[:id])
    @item.update(archived: true)
    redirect_to farm_items_path, notice: "Item removed"
  end

  def new
    @item = Item.new
    @item.images.build
    @categories = Category.all.where("parent_id IS NOT null").map do |category|
      [category.name, category.id]
    end
  end

  def edit
    @item = Item.find(params[:id])
    @categories = get_categories_list
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)

    if @item.valid?
      redirect_to farm_items_path, notice: "Item updated successfully"
    else
      redirect_to farm_items_path, notice: "Could not update item"
    end
  end

  def product
    @item = Item.find(params[:id])
    @categories = get_categories_list
  end

  def farm_index
    @items = current_farm.items.live.order(name: "ASC").paginate(page: params[:page]).includes(:images)
  end

  def item_params
    params.require(:item).permit(:name, :quantity, :price, :farm_id, :category_id, :description,
      images_attributes: [:id, :image, :item, :_destroy])
  end

  def get_categories_list
    Category.all.where("parent_id IS NOT null").map do |category|
          [category.name, category.id]
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_image_fields.html.haml
.nested-fields
  .itemImage
    = image_tag f.object.image.url :thumb unless f.object.image.url.nil?
  = label_tag "Select Image"
  = f.file_field :image
  = link_to_remove_association "Remove Image", f

app/views/items/_item.html.haml
.itemForm
  = form_for @item do |f|
    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :price
      = f.number_field :price, min: 0.10, step: "any"
    .field
      = f.label :quantity
      = f.number_field :quantity, min: 1
    .field
      = f.label :category_id
      = f.select :category_id, @categories, {}, class: "browser-default"
    .field
      = f.label :description
      = f.text_area :description
    .images
      = f.fields_for :images do |builder|
        = render "image_fields", { f: builder }
      = link_to_add_association "Add Image", f, :images

    = f.hidden_field :farm_id, value: current_farm.id
    .field
      = f.submit

app/views/items/edit.html.haml
%h1 Edit Item

= render "item"

app/views/items/farm_index.html.haml
= render "page_title", title_text: "My Items"

.row
  %a{href: new_item_path, class: "waves-effect waves-light btn blue darken-2 col s3 offset-s9"}
    %i{class: "material-icons left"} library_add
    Add an Item

.inventoryContainer
  - @items.each do |item|
    .card{class: "teal lighten-5"}
      .item{id: "item_#{item.id}", class: "card-content"}
        .itemName{class: "card-title"}
          = item.name
        .itemPrice £#{item.price} each
        .itemQuantity Quantity: #{item.quantity}
        .card-action
          %a{href: "#{edit_item_path(id: item.id)}", class: "editItemButton waves-effect waves-light btn"}
            %i{class: "material-icons left"} mode_edit
            Edit
          %a{href: "/items/#{item.id}", class: "deleteItemButton waves-effect waves-light btn red", method: :delete}
            %i{class: "material-icons left"} delete
            Delete

app/views/items/new.html.haml
%h1 Add a New Item

= render "item"

app/views/items/product.html.haml
%h1
  =@item.name

.productDetails
  .productImages
    = # Add carousel here
  .productPrice
    £
    = @item.price
  .productDescription
    = @item.description
  %label Quantity
  %input{type: "text", class: "productQuantityInput"}
  / TODO: Implement angular here so can use handle bars or use javascript ajax
  = link_to "Add to Basket", baskets_path, method: :post