config/routes.rb
Rails.application.routes.draw do

  devise_for :farms, controllers: { omniauth_callbacks: "farm_callbacks" }
  devise_for :restaurants

  authenticated :farm do
    root "farms#index", as: :farm_root
    get "/" => "farms#index"
  end

  authenticated :restaurant do
    root "restaurants#index", as: :restaurant_root
    get "/" => "restaurants#index"
  end

  root "application#index"

  resources :categories, only: [:index]
  resources :items, only: [:index, :create, :show, :update, :destroy, :new, :edit]
  resources :baskets, only: [:index, :create, :destroy, :update]
  resources :charges, only: [:new, :create]
  resources :orders, only: [:index, :create, :show]

  get "/baskets/count" => "baskets#count"
  get "/inventory" => "items#farm_index", as: :farm_items
  get "/product/:id" => "items#product", as: :product
  get "/map" => "maps#index", as: :map
  get "/farms/:id/items" => "farms#show", as: :farms_items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def index

  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :password, :password_confirmation, :current_password, :name, :type,
               :street, :city, :post_code, :region, :logo)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:email, :password, :password_confirmation, :current_password, :name, :type,
               :street, :city, :post_code, :region, :logo)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_farm_menu.html.haml
%ul{id: "nav-mobile", class: "right hide-on-med-and-down"}
  %li #{link_to "Inventory", farm_items_path}
  %li #{link_to "Profile", edit_farm_registration_path}
  %li #{link_to "Sign Out", destroy_farm_session_path, method: :delete}

app/views/application/_guest_menu.html.haml
%ul{id: "nav-mobile", class: "right hide-on-med-and-down"}
  %li #{link_to "Farm Sign In", new_farm_session_path, {class: "waves-effect waves-light btn light-blue darken-3"}}
  %li #{link_to "Restaurant Sign In", new_restaurant_session_path, { class: "waves-effect waves-light btn red accent-2"}}

app/views/application/_page_title.html.haml
.row
  .section
    %h2{class: "teal-text"} #{title_text}
  .divider

app/views/application/_restaurant_menu.html.haml
%ul{id: "nav-mobile", class: "right hide-on-small-and-down"}
  %li #{link_to "Home", restaurant_root_path, {"data-no-turbolink": true}}
  %li #{link_to "Profile", edit_restaurant_registration_path}
  %li #{link_to "Orders", orders_path}
  %li #{link_to "Sign Out", destroy_restaurant_session_path, method: :delete}
  %li #{link_to "Farms near me", map_path, { "data-no-turbolink": true, class: "map_pathwaves-effect waves-light btn deep-orange darken-1"}}
  %li{id: "basketItem"}
    #basketContainer
      %a{href: baskets_path, "data-no-turbolink": true}
        %i{id: "basket", class: "material-icons"} shopping_cart

    #basketCountContainer
      %span{id: "basketCount"}

%span{id: "basketNotify"} Item added to basket.

app/views/application/_sub_section_header.html.haml
.row
  .section
    %h4 #{section_title}
  .divider

app/views/application/index.html.haml
#landing-background

.row
  .promo-box{class: "col s10 offset-s1 white-text"}
    %h1 Farm Fresh
    %h4 Connecting restaurants with their local farmers.

.row
  .promo-container{class: "col s10 offset-s1"}
    .row
      %div{class: "promo col s4"}
        %img{src: "https://s3-eu-west-1.amazonaws.com/kpfarmfresh/promo_farm.png"}
        %h5 Find customers for your produce
        = link_to "Register Farm", new_farm_registration_path, class: "waves-effect waves-light btn-large light-blue darken-3"
      %div{class: "promo col s4 offset-s4"}
        %img{src: "https://s3-eu-west-1.amazonaws.com/kpfarmfresh/promo_restaurant.png"}
        %h5 Find the freshest, local ingredients
        = link_to "Register Restaurant", new_restaurant_registration_path, class: "waves-effect waves-light btn-large red accent-2"